version: "3.0"    # tag 명

services:         # 기본 문법
  python-app:     # services 명
    build: .      # Dockerfile의 경로
    image: ${DOCKER_USR}/hw6_acha
    ports:     
      - "80:80"   # 포트 번호를 이어줌
    volumes:
      - ./app:/app